name: Node.js Dev CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch: # 수동 실행도 가능하도록 함

jobs:
  deploy:
    runs-on: ubuntu-latest # 우분투 최신 버전으로 실행

    steps:
      # Checkout the code
      - name: Checkout
        uses: actions/checkout@v3

      # Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_EC2_HOST }}  # EC2 호스트 (IP 또는 도메인)
          username: ${{ secrets.AWS_EC2_USER }}  # EC2 사용자 이름 (예: ec2-user)
          key: ${{ secrets.AWS_EC2_KEY }}  # GitHub Secrets에 저장된 EC2 SSH 개인 키
          script: |
            cd /home/$USER/lol  # EC2에서 작업할 디렉터리로 이동
            git pull origin main  # main 브랜치에서 최신 코드 가져오기
            if ! command -v node &> /dev/null; then
              curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -  # Node.js 설치
              sudo apt install -y nodejs
            fi
            if ! command -v npm &> /dev/null; then
              sudo apt install -y npm  # npm 설치
            fi
            npm ci  # 의존성 설치 (package-lock.json에 맞게)
            npx pm2 restart /home/$USER/lol/bin/www.js --name "my-app"  # pm2로 bin/www.js 실행
